/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : test-path-name
 #	author : miyako
 #	2018/07/09
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONWIN
#include <Shlwapi.h>
#include <Process.h>//_beginthreadex
#include <Rpc.h> //UuidCreateSequential
#endif

// --- shlwapi
void shlwapi_Test_path_name(sLONG_PTR *pResult, PackagePtr pParams);

typedef enum
{
	is_a_folder = 0,
	is_a_document = 1,
	does_not_exist = -43
}test_path_name_result;

typedef struct
{
	test_path_name_result value;
}test_path_name_result_t;

#define MAX_PATH_LENGTH 32767
#define UUID_LENGTH 40
#define WAIT_TIMEOUT_MS 100
#define PARAM_NAME_OUT L"test_path_name_OUT"
#define PARAM_NAME_IN L"test_path_name_IN"
#define CMD_IDLE 311

/* https://docs.microsoft.com/ja-jp/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation */
typedef struct
{
	wchar_t path[MAX_PATH_LENGTH];
	wchar_t a[UUID_LENGTH];
	wchar_t b[UUID_LENGTH];
	
}test_path_name_param_t;
